export const CREATE_COUNTRY = "CREATE_COUNTRY";
export const RETRIEVE_COUNTRYS = "RETRIEVE_COUNTRYS";
export const UPDATE_COUNTRY = "UPDATE_COUNTRY";
export const DELETE_COUNTRY = "DELETE_COUNTRY";
export const DELETE_ALL_COUNTRYS = "DELETE_ALL_COUNTRYS";